/* automatically generated by rust-bindgen 0.69.5 */

use crate::sqlite3;

pub const SQLITE_RECOVER_LOST_AND_FOUND: u32 = 1;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct sqlite3_recover {
    _unused: [u8; 0],
}
extern "C" {
    pub fn sqlite3_recover_init_sql(
        db: *mut sqlite3,
        zDb: *const ::std::os::raw::c_char,
        xSql: ::std::option::Option<
            unsafe extern "C" fn(
                arg1: *mut ::std::os::raw::c_void,
                arg2: *const ::std::os::raw::c_char,
            ) -> ::std::os::raw::c_int,
        >,
        pCtx: *mut ::std::os::raw::c_void,
    ) -> *mut sqlite3_recover;
}
extern "C" {
    pub fn sqlite3_recover_config(
        arg1: *mut sqlite3_recover,
        op: ::std::os::raw::c_int,
        pArg: *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn sqlite3_recover_run(arg1: *mut sqlite3_recover) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn sqlite3_recover_errmsg(arg1: *mut sqlite3_recover) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn sqlite3_recover_finish(arg1: *mut sqlite3_recover) -> ::std::os::raw::c_int;
}
